### ISSUE TITLE
Aria passive system: Problem with LocationInformationRequest (only 1000) and strange behaviour in ExchangePointRequest.

### ISSUE THREAD

**Issue by ue71603** [LinkingAlps/Main#20]
Only 1000 StopPlaces are delivered even when ContinueAt is used. and it ignores the NumberOfResults 
See attached word and postman collection.

**Comment by ue71603** [comment]
[ARIA_LIR_Problem.docx](https://github.com/LinkingAlps/Main/files/7176287/ARIA_LIR_Problem.docx)
[LA-Passiv_zu_Aria.postman_collection.zip](https://github.com/LinkingAlps/Main/files/7176292/LA-Passiv_zu_Aria.postman_collection.zip)

**Comment by sbarassi** [comment]
The issue with LocationInformationRequest has been solved.
We are still working on ExchangePointRequest.

**Comment by sbarassi** [comment]
The issue with ExchangePointRequest has been solved as well.

**Comment by sbarassi** [comment]
The issue can be closed

**Comment by rcavaliere** [comment]
@sbarassi if I test the EPR I still get a lot of EP. Is this wanted? I am trying with an empty request

**Comment by sbarassi** [comment]
> 

@rcavaliere yes, data are not updated yet...
